name: RF Lint

on:
  pull_request:
    branches: [ master, homol ]

jobs:
   Lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Robot Framework Lint
          uses: carlosnizolli/RobotLint@v2.3
          with:
             robot-files: Exemplos
