name: Roda Exemplos

on:
  pull_request:
    branches: [ master, homol ]
    
jobs: 
   Lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Robot Framework Lint
          uses: carlosnizolli/RobotLint@v2.3
          with:
             robot-files: Exemplos
   BuiltIn:
        runs-on: ubuntu-latest
        needs: Lint
        steps:   
        - uses: actions/checkout@v2
        - name: Create folder for reports
          run:  mkdir -m 777 reports
        - name: Execute Robot tests
          uses: carlosnizolli/robotframework-docker-action@browser
          env:
            DOCKER_SHM_SIZE: 11000000
            ROBOT_TESTS_DIR: ${{ github.workspace }}/Exemplos/BuiltIn/Tests
            ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
            ROBOT_OPTIONS: "--name BuiltIn"
           
            
        - name: Upload test to artifact
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: BuiltIn
            path: ${{ github.workspace }}/reports
   Mobile:
        runs-on: ubuntu-latest
        needs: Lint
        steps:   
          - uses: actions/checkout@v2
          
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: "3.9.1"
              architecture: "x64"
              
          - name: Yarn Install
            uses: actions/setup-node@v1
            with:
                node-version: 12.x     
            
          - name: Set up JDK 1.8
            uses: actions/setup-java@v1
            with:
              java-version: 1.8

          - name: Setup Android SDK
            uses: android-actions/setup-android@v2   
          
          - name: Install and run Emulator
            run: |
              sdkmanager "platforms;android-22"
              sdkmanager "system-images;android-22;default;x86_64"
              sdkmanager "emulator"
              sdkmanager "platform-tools"
              avdmanager create avd\
               -n Android\
               -k "system-images;android-22;default;x86_64"\
               --device "Nexus 5"\
               --sdcard 100M 
              avdmanager --verbose list device 
              
          - name: Install and Run Appium Server
            run: |
              npm install -g appium
              appium &

            
          - name: Create folder for reports
            run:  mkdir -m 777 reports
            
          - name: Robot Install   
            run: |
              pip3 install robotframework
              pip3 install robotframework-browser
              pip3 install robotframework-appiumlibrary
              rfbrowser init
              
          - name: Execute Robot tests
            run: robot -d ${{ github.workspace }}/reports ${{ github.workspace }}/Exemplos/Appium/tests.robot
             
          - name: Upload test to artifact
            uses: actions/upload-artifact@v1
            if: always()
            with:
              name: Mobile
              path: ${{ github.workspace }}/reports
