name: Roda Exemplos

on:
  pull_request:
    branches: [ master, homol ]
    
jobs: 
   Lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Robot Framework Lint
          uses: carlosnizolli/RobotLint@v2.3
          with:
             robot-files: Exemplos
   RunKwIF:
        runs-on: ubuntu-latest
        needs: Lint
        steps:   
        - uses: actions/checkout@v2
        - name: Create folder for reports
          run:  mkdir -m 777 reports
        - name: Execute Robot tests
          uses: carlosnizolli/robotframework-docker-action@browser
          env:
            DOCKER_SHM_SIZE: 11000000
            ROBOT_TESTS_DIR: ${{ github.workspace }}/Exemplos/RunKWIf/Tests
            ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
           
            
        - name: Upload test to artifact
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: RunKWIf
            path: ${{ github.workspace }}/reports
